import os

from dotenv import load_dotenv

load_dotenv()

DEFAULT_API_HISTORY = os.getenv('DEFAULT_API_HISTORY')
DEFAULT_API_FORECAST_MINUTE = os.getenv('DEFAULT_API_FORECAST_MINUTE')
DEFAULT_API_FORECAST_HOURLY = os.getenv('DEFAULT_API_FORECAST_HOURLY')
DEFAULT_API_FORECAST_DAILY = os.getenv('DEFAULT_API_FORECAST_DAILY')
DEFAULT_API_CURRENT = os.getenv('DEFAULT_API_CURRENT')
DEFAULT_API_KEY = os.getenv('DEFAULT_API_KEY')
